name: xover
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - xarray
  - zarr
  - dask
  - dask_kubernetes
  - intake
  - numpy
  - numpy_groupies
  - netCDF4
  - scipy
  - pandas
  - matplotlib
  - cartopy
  - xrft
  - xgcm
  - xmitgcm
  - gsw
  - pip
