name: xover
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - numpy_groupies
  - scipy
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs=8.
  - xmitgcm
  - xgcm
  - xrft
  - xhistogram
  - cartopy
  - gsw
  - pip:
    - kubernetes
    - graphviz
    - jupyterlab_widgets
