name: xover
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - numpy_groupies
  - scipy
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab
  - jupyter_client
  - dask_labextension
  - ipywidgets
  - graphviz
  - nodejs
  - xmitgcm
  - xgcm
  - xrft
  - xhistogram
  - cartopy
  - gsw
  - pip:
    - kubernetes
    - graphviz
